### ISSUE TITLE
Mideo on Windows

### ISSUE THREAD

**Issue by wesrub02** [jwktje/mideo#1]
I'm not very familiar with GitHub. But I was asked to leave an issue under the GitHub repo as a reminder for making Mideo compatible with Windows. I hope I've done it correctly.

**Comment by fabislost** [comment]
I just tried it on windows using electron-prebuilt, doesn't seem to work very well, I would try to make it work on windows but I don't have any mac to see how it actually works and thus no motivation lmao. Hope @jwktje will look into this...or somebody else

**Comment by jwktje** [comment]
Thanks for following up and creating this issue! This is a good place to keep track of progress. I'm currently traveling the world, hence why I mentioned in the YT comments that I don't have access to a windows machine. 

I will attempt a build for windows, and then you guys could maybe test if it's working like it should.

**Comment by jwktje** [comment]
I just published another release on this repository that has my attempt at a Windows build. I was easily able to build it but I have no idea if it works without a hitch. Please test it and let me know what you find. (optionally) also check the Ableton documentation linked in the README for this repo. It explains some stuff about virtual midi busses that you might also need to use Mideo.

You can find the release here: https://github.com/jwktje/mideo/releases/tag/0.0.7

**Comment by wesrub02** [comment]
Heel erg bedankt. Ik heb nu helaas nog school, maar ik zal het vanmiddag
testen en dan hoor je wel of het goed werkt.

Groetjes,
Wessel

Op di 12 feb. 2019 01:07 schreef Jan Willem Kolkman <
notifications@github.com:

**Comment by wesrub02** [comment]
Hello jwktje,

I've tested the application on a Windows device and it seems to work just
fine. I did not come across any bugs. Thank you for taking the time to make
this work.

Wessel

Op di 12 feb. 2019 07:08 schreef Wessel Molenbroek <wrm.xtra@gmail.com:

**Comment by jwktje** [comment]
That is great! I'll keep this issue open for now, just to wait and see if others might have small bugs. Issue #2 for instance occurs. 

Thanks for reporting @wesrub02 👍

**Comment by fabislost** [comment]
Works really well! I don't know why it didn't work with electron-prebuilt when i tried it though, weird

**Comment by Itsman-AT** [comment]
Does it actually need the network connection it is asking permission for in the beginning? I denied it and nothing seems to happen, just the video is running and the grid is showing.

**Comment by jwktje** [comment]
@Itsman-AT It's built on Electron which means it ships with an embedded browser. This is probably why it would trigger a network connection request. You can allow or deny it. I'm sure you should be fine either way, functionality wise.

**Comment by DBraspberrypi** [comment]
Does this work on Linux??

**Comment by jwktje** [comment]
@DBraspberrypi Probably, I didn't test. I think the code should run on Linux.
