### ISSUE TITLE
Mideo on Windows Javascript Error

### ISSUE THREAD

**Issue by PatrickMitchellUI** [jwktje/mideo#2]
When running the windows release on windows 10 (17763.292) a Javascript error is is thrown on launch. the program continues to run but does not successfully track any colors (see screenshots). It only picks up the first match but none after that
![image](https://user-images.githubusercontent.com/14038874/52604281-2a4d1400-2eba-11e9-964f-9de5dadff8c9.png)
![image](https://user-images.githubusercontent.com/14038874/52604310-4bae0000-2eba-11e9-88b5-7dd09a4ec4c3.png)

**Comment by PatrickMitchellUI** [comment]
I realise the second screenshot is a bad example as there is a firework in the frame but trust me it doesnt work :)

**Comment by jwktje** [comment]
Thanks for reporting! Is there a chance you are running software that is using port 3003 on your machine? I see an address in use error. 

If you are not sure, we should try and get a second person to test on their machine. Or you test it on another machine.

**Comment by jwktje** [comment]
Another user reported being able to use it without problems on his Windows machine. My best guess is that you are indeed running some sort of software on port 3003 already, causing this error. 

Maybe check this StackOverflow answer to find out which process it might be: https://stackoverflow.com/a/48199/1278272

**Comment by PatrickMitchellUI** [comment]
after checking this I found no programs  running on this port

**Comment by jwktje** [comment]
Do you have another windows system to test on if the program runs?

**Comment by PatrickMitchellUI** [comment]
tried on a fresh install machine, still no luck, could be related to windows build or type

**Comment by jwktje** [comment]
Did you get the exact same error on another machine? That is very very strange. 
Maybe try running the application without using the built .EXE.

So: 
1. (optional first step) Have Node.js (with NPM) installed
2. Download/Clone the repository locally
3. Run `npm install` in the root of the directory and wait a bit
4. Then run `npm run start` and see if the application runs

**Comment by PatrickMitchellUI** [comment]
![image](https://user-images.githubusercontent.com/14038874/53704977-18cfaa00-3e71-11e9-8d60-2058c4c2febd.png)
running Mideo from sources just produces a broken ui with no functionality

**Comment by jwktje** [comment]
Ah but it is generating errors I see! Could you copy and paste (or screenshot) the output on the “console” tab of the “Developers tools” window?

That would really help narrow down what is going wrong

**Comment by PatrickMitchellUI** [comment]
```
 npm run start

> Mideo@0.0.7 start C:\Users\Patrick Mitchell\mideo
> electron .


 Express server listening on port 3003
```

**Comment by jwktje** [comment]
Are you sure there is not more output in the Console tab of the Developer Tools? I mean in the two screens that open when you run. Your previous screenshots show 5 errors being thrown (visible in the top right. The red X with the number 5). That is the output i'm interested in.
