### ISSUE TITLE
Output_name problems

### ISSUE THREAD

**Issue by ratilomend** [jwktje/mideo#3]
Hi,

I've managed to get Mideo running okay on both my Macs (one running Mojave and the other running Sierra), I can load a video and tweak the settings in the controls but when I click on the output_name dropdown nothing happens. 
I'm not sure if this is a bug or if I'm just doing something wrong?

Thanks!

**Comment by jwktje** [comment]
It is supposed to show available midi outputs, like so:
<img width="258" alt="screenshot 2019-02-18 at 17 12 32" src="https://user-images.githubusercontent.com/4722137/52978747-90490800-33a0-11e9-92ea-a345fa0f2869.png">

Did you read the last section of the Readme? This explains this and has a link to an Ableton article that shows how to set them up.

**Comment by ratilomend** [comment]
Ah okay, I see, thank you!
