### ISSUE TITLE
No sound output

### ISSUE THREAD

**Issue by JolleJolles** [jwktje/mideo#5]
Hi, I am very interested in using your software, but although I can get a video to run and can click on the settings I don't hear anything, even with a dummy video that just has a white background and a big red moving dot. Also the box with output_name does not work.

I am a biologist working with animals and am working on a project to create music from the movements of individuals and groups of fish using custom developed tracking software, so was interested to see this project!

Thanks

**Comment by jwktje** [comment]
I feel like you are somewhat mistaken. The application generates Midi data, not sound. Check the Readme about the virtual midi bus. 
https://github.com/jwktje/mideo#virtual-midi-bus-

**Comment by JolleJolles** [comment]
Sorry I meant midi (to create sound). But the software doesn't output anything see [screenshot](https://www.dropbox.com/s/ovpj8sooxplz4k1/mideo-screenshot.png?dl=0). Maybe I am missing something? Thanks for helping. Have you tried creating similar software with python?

**Comment by jwktje** [comment]
You probably still misunderstand something here. For example; you can't take a screenshot of your network data going to your WiFi antenna either right? So likewise you can't screenshot this software and prove that no midi is being sent. 

Again I advice you to look to the Readme and setup a virtual midi bus towards other software that receives it and turns it into sound.

If I'm right to assume, you think Midi is only a file. But midi is a standard for communication. Yes, there are also midi files but that is not what Mideo generates. It generates midi data in realtime and sends it out

**Comment by JolleJolles** [comment]
I can of course take a screenshot of your software interface to show you something.. but its fine I will try something else
